spring.application.name=reservation-service
server.port=8080

#MYSQL connection details
spring.datasource.url=jdbc:mysql://localhost:3306/reservation_db
spring.datasource.username=root
spring.datasource.password=MYSQL@123
spring.jpa.hibernate.ddl-auto=update

#Actuator EndPoints

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted

#Log Output Format

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n